# Assignment 2: NumPy
- **you will learn:** how to create and manipulate NumPy arrays, perform vectorized computations, and use basic NumPy functions for data analysis
- **task:**  See section 2.9 below
- **deadline:** 20.10.2025
- [NumPy documentation](https://numpy.org/doc/stable/)
- 📝 **Reminder:** Sync your GitHub repository with the main course repository, update your project in PyCharm, and after completing the assignment, commit and push your changes back to GitHub.
---

## 2.0 PEP 8 and Code Commenting

### What is PEP 8?
**PEP 8** is the official **style guide** for Python code.
It defines conventions that make your code **clean, consistent, and easy to read**.
While not mandatory, following PEP 8 is considered a sign of **professional and readable coding**.

### Some Important PEP 8 Rules
- ✅ **Line length:** keep lines **under 79 characters**.
- ✅ **Spacing:**
  - add spaces around operators (`a + b`, not `a+b`)
  - add a space **after** commas, not before (`[1, 2, 3]`, not `[1 ,2 ,3]`)
- ✅ **Variable and function names:** use lowercase with underscores (`calculate_mean`, not `CalculateMean`).
- ✅ **Class names:** use `CamelCase` (`DataProcessor`).
- ✅ **Imports:** at the top of the file, one per line.
- ✅ **Blank lines:** use two blank lines between functions.

 **Official guide:** [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/)

### Comments and Docstrings
Comments explain **what** your code does and **why**.
Every function should include a **docstring** — a text enclosed in triple quotes `""" ... """` that briefly describes the function’s purpose, parameters, and return value.

#### Example:

```python
def calculate_mean(values):
    """
    Compute the arithmetic mean of a list of numbers.

    Parameters
    ----------
    values : list of float
        Input numbers.

    Returns
    -------
    float
        The arithmetic mean of the input values.
    """
    if not values:
        return 0.0
    return sum(values) / len(values)



---
## 2.1 What is a NumPy Array?

- In computer programming, an **array** is a structure for storing and retrieving data.
- They are the foundation for **data science, machine learning, and scientific computing** in Python.
- We often visualize an array as a **grid in space**, with each cell storing one element of data.
- Arrays can be **1D (vectors), 2D (matrices), or higher-dimensional (tensors)**.

Most NumPy arrays have some rules:

1. **Homogeneous type:** All elements must be of the same data type.
2. **Fixed size:** Once created, the total size cannot change.
3. **Rectangular shape:** All rows (in 2D arrays) must have the same number of columns — no jagged arrays.

When these conditions are met, NumPy can exploit them to make arrays:

- **Faster** (optimized C loops under the hood)
- **More memory efficient** (contiguous memory storage)
- **More convenient to use** (vectorized operations without explicit loops)

In [6]:
import numpy as np
print(np.__version__)

2.3.4


In [ ]:
# Create 1D array (vector)
vector = np.array([10, 20, 30, 40, 50])
print("1D array (vector):", vector)
print("Shape:", vector.shape, "Dtype:", vector.dtype)

# Create 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("2D array (matrix):\n", matrix)
print("Shape:", matrix.shape, "Dtype:", matrix.dtype)

# Vectorized operation: multiply all elements by 2 or square them
matrix2 = 2 * matrix
matrix_sq = matrix ** 2
print("Matrix after multiplying by 2:\n", matrix2)
print("Matrix after squaring by 2:\n", matrix_sq)

---
## 2.2 Constructing arrays

There are several mechanisms for creating arrays. Among others:

1. **Conversion from other Python structures**
   Arrays can be created directly from existing **lists or tuples** using `np.array()`.
   This is the most common and straightforward way to build an array from existing data.

In [ ]:
# Conversion from Python structures
a = np.array([1, 2, 3, 4, 5])
b= np.array(((1,0),(0,1)))
c = np.array([([1,2],[2,1]), ([3,1],[1,3])])
print("From list:\n", a)
print("From tuples of tuples:\n", b)
print("From list of tuples or lists:\n", c)


2. **NumPy array creation functions**
   NumPy provides a set of **built-in constructors** such as `np.zeros`, `np.ones`, `np.arange`, and `np.linspace`
   to generate arrays of a specific shape or with evenly spaced values.

In [ ]:
# np.empty(shape, dtype)
# Creates a new array *without initializing* its entries (values are arbitrary).
arr_empty = np.empty((2,3), dtype="int32")
print("np.empty:\n", arr_empty)
print("np.empty type:", arr_empty.dtype)

In [ ]:
# np.identity(n)
# Shortcut for creating a square identity matrix (ones on the main diagonal).
arr_identity = np.identity(4)
print("np.identity:\n", arr_identity)

In [ ]:
# np.eye(N, M, k)
# Creates a 2D array with ones on the main (or k-th) diagonal, zeros elsewhere.
arr_eye = np.eye(4,4,-1)
print("np.eye:\n", arr_eye)

In [ ]:
# np.ones(shape, dtype)
# Creates an array of given shape filled with ones.
arr_ones = np.ones((2, 4))
print("np.ones:\n", arr_ones)

In [ ]:
# np.zeros(shape, dtype)
# Creates an array filled with zeros.
arr_zeros = np.zeros((3, 3))
print("np.zeros:\n", arr_zeros)

In [ ]:
# np.full(shape, fill_value)
# Creates an array filled with a specified constant value.
arr_full = np.full((2, 3), fill_value=7)
print("np.full:\n", arr_full)

In [ ]:
# np.empty_like(prototype)
# Creates an uninitialized array with the *same shape and dtype* as another array.
prototype = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
arr_zeros_like = np.zeros_like(prototype)
print("np.empty_like:\n", arr_zeros_like)

# Similarly with np.empty_like(a), np.zeros_like(a), np.full_like(a, fill_value)

In [ ]:
# np.arange([start,] stop[, step,][, dtype])
# Returns evenly spaced values within a given interval.
# Similar to Python's range(), but returns a NumPy array.
arr_arange = np.arange(0, 10, 2, dtype=float)
print("np.arange:\n", arr_arange)

In [ ]:
# np.linspace(start, stop[, num, endpoint])
# Returns evenly spaced numbers over a specified interval.
# Unlike arange, it lets you specify the number of samples.
arr_linspace = np.linspace(0, 1, num=5)
print("np.linspace:\n", arr_linspace)

In [ ]:
# np.diag(v[, k])
# Construct a diagonal matrix from a 1D array, or extract a diagonal from a 2D array.
v = np.array([1, 2, 3])
arr_diag = np.diag(v)
print("np.diag (construct from 1D):\n", arr_diag)

In [ ]:
# np.tril(m[, k])
# Return the lower triangle of an array (elements above the k-th diagonal are zeroed).
m = np.arange(1, 10).reshape(3, 3)
arr_tril = np.tril(m)
print("np.tril (lower triangle):\n", arr_tril)

# similarly with np.triu(m[, k])


3. **Replicating, joining, or mutating existing arrays**
   Arrays can be **copied, concatenated, reshaped, or repeated** to create new ones.
   For example, you can use `np.tile`, `np.concatenate`, or `reshape` for this purpose.

In [ ]:
# np.reshape(a, newshape)
# Changes the shape of an array without changing its data.
a = np.arange(6)
print("a:\n", a)
reshaped = np.reshape(a, (3, 2))
print("np.reshape:\n", reshaped)

In [ ]:
# a.flatten()
# Flatten a multi-dimensional array into 1D.
a2 = np.array([[1, 2], [3, 4]])
print("a.flatten:\n", a2.flatten())

In [ ]:
# np.transpose(a) or a.T
# Swaps axes, e.g., turns rows into columns.
print("np.transpose:\n", np.transpose(a2))

In [ ]:
# np.swapaxes(a, axis1, axis2)
# Swaps any two axes in a multi-dimensional array.
a3 = np.arange(8).reshape(2, 2, 2)
print("a3:\n", a3)
print("np.swapaxes:\n", np.swapaxes(a3, 0, 2))

In [ ]:
# np.moveaxis(a, source, destination)
# Moves a given axis to a new position.
a4 = np.zeros((2, 3, 4))
print("np.moveaxis shape:", np.moveaxis(a4, 0, -1).shape)

In [ ]:
# np.squeeze(a)
# Removes axes of length 1.
a5 = np.zeros((1, 3, 1))
print("a5:\n", a5)
print("np.squeeze shape:", np.squeeze(a5).shape)
print("a5 squeezed:\n", np.squeeze(a5))

In [ ]:
# np.expand_dims(a, axis)
# Adds a new dimension (axis) to the array.
a6 = np.array([1, 2, 3])
print("np.expand_dims shape:", np.expand_dims(a6, axis=0).shape)

In [ ]:
# np.concatenate((a1, a2, ...), axis)
# Joins arrays along an existing axis.
a7 = np.ones((2, 2))
b7 = np.zeros((2, 2))
print("np.concatenate:\n", np.concatenate((a7, b7), axis=1))

In [ ]:
# np.stack((a1, a2, ...), axis)
# Stacks arrays along a new axis.
a8 = np.array([1, 2])
b8 = np.array([3, 4])
print("np.stack:\n", np.stack((a8, b8), axis=0))

In [ ]:
# np.split(a, sections, axis)
# Splits an array into multiple subarrays.
x = np.arange(9)
print("np.split:\n", np.split(x, 3))

In [ ]:
# np.copy(a)
# Creates a deep copy of the array (independent of the original).
a11 = np.array([1, 2, 3])
b11 = a11.copy()
b11[0] = 99
print("Original:", a11, " | Copy:", b11)

In [ ]:
# np.astype(dtype)
# Converts array elements to a new type.
a12 = np.array([1, 2, 3])
print("astype to float:\n", a12.astype(float))

In [ ]:
# np.clip(a, min, max)
# Limits values to a given range.
a13 = np.array([-1, 0, 2, 5])
print("np.clip:\n", np.clip(a13, 0, 3))

In [ ]:
# np.where(condition, x, y)
# Selects elements based on a condition.
a14 = np.array([1, 2, 3])
print("np.where (a > 1 -> 100):\n", np.where(a14 > 1, 100, a14))


4. **Creating Arrays from Other Libraries**

Many Python libraries — such as **SciPy**, **Pandas**, and **OpenCV** — use NumPy `ndarray` objects as a **common format for data exchange**.
These libraries can **create**, **manipulate**, and **interoperate with** NumPy arrays directly.


---
## 2.3 Indexing arrays

Note that Python indexes (unlike for example R) start from 0, not from 1.

### Basic Indexing

In [ ]:
# Create a 2D array for demonstration
x = np.arange(1, 13).reshape(3, 4)
print("Array x:\n", x)

# 1. Single element indexing
print("Single element x[1, 2]:", x[1, 2])
print("Same by chained indexing x[1][2]:", x[1][2])

In [ ]:
# 2. If fewer indices than dimensions, returns a subarray (view)
print("x[0] returns first row (view):", x[0])

In [ ]:
# 3. Slicing (rows, columns)
print("x[0:2, 1:4] → rows 0 and 1, columns 1 to 3:\n", x[0:2, 1:4])

In [ ]:
# 4. Striding with step (convention start:stop:step)
print("x[:, ::2] → all rows, every second column:\n", x[:, ::2])

In [ ]:
# 5. Using negative indices
print("x[-1, -2]:", x[-1, -2])  # last row, second-last column

In [ ]:
# 6. Ellipsis (`...`) and `newaxis` (alias None)
# Ellipsis expands to as many ":" as needed
print("x[..., 2] → same as x[:, 2]:", x[..., 2])

# newaxis introduces a new dimension
y = x[:, 1]  # shape (3,)
y2 = x[:, 1, np.newaxis]  # shape (3,1)
print("y shape:", y.shape, "   y2 shape:", y2.shape)

- All slicing operations produce views, not copies — they refer to the same underlying data.
- Because of this, modifying a slice will affect the original array.
- When using integer indexing (not slicing), you reduce a dimension.
- : means “select all elements along this axis”.
- ... is a convenient placeholder to fill in missing : for remaining axes.

### Advanced Indexing

In [69]:
x = np.arange(1, 13).reshape(3, 4)
print("Array x:\n", x)

# 1. Integer array indexing
row_idx = [0, 2]
col_idx = [1, 3]
# Select elements (0,1) and (2,3)
print("x[row_idx, col_idx]:", x[row_idx, col_idx])

# Equivalent as
print("The same as:", np.array([x[0,1],x[2,3]]))

Array x:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x[row_idx, col_idx]: [ 2 12]
The same as: [ 2 12]


In [70]:
# 2. Broadcasting integer indices
# If you supply fewer index arrays or scalars, they broadcast
print("x[row_idx, 2]:", x[row_idx, 2])
print("The same as:", x[[0,2], [2,2]])

x[row_idx, 2]: [ 3 11]
The same as: [ 3 11]


In [71]:
# 3. Boolean masking (Boolean indexing)
mask = x % 2 == 0  # True for even numbers
print("Boolean mask:\n", mask)
print("x[mask] → all even elements:", x[mask])

# Example modification using Boolean mask
x2 = x.copy()
x2[x2 % 2 == 1] = -1
print("x2 with odd elements replaced by –1:\n", x2)

Boolean mask:
 [[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
x[mask] → all even elements: [ 2  4  6  8 10 12]
x2 with odd elements replaced by –1:
 [[-1  2 -1  4]
 [-1  6 -1  8]
 [-1 10 -1 12]]


In [ ]:
# 4. Combining basic and advanced indexing
# e.g. select rows 0 and 2, but columns 1:3
print("x[[0, 2], 1:3]:\n", x[[0, 2], 1:3])

---
## 2.4 Array attributes

- Every NumPy array is a Python object of class `numpy.ndarray`.
- Besides storing the actual data, it also stores various attributes that describe its structure and memory layout.

In [ ]:
# Let's create a simple 2D array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print("Type of numpy array object:", type(a))

In [ ]:
print("Number of dimensions (ndim):", a.ndim)
print("Shape (rows, columns):", a.shape)
print("Total number of elements (size):", a.size)
print("Data type (dtype):", a.dtype)
print("Size of one element in bytes (itemsize):", a.itemsize)
print("Total size in bytes (nbytes):", a.nbytes)
print("Transposed array (T):\n", a.T)

Example explanation:
- ndim   → tells how many axes (dimensions) the array has
- shape  → gives the length of each dimension as a tuple
- size   → total count of elements = product of shape entries
- dtype  → data type of the elements (e.g. int32, float64)
- itemsize → bytes per element, depends on dtype
- nbytes   → total memory used by the array
- T        → shorthand for the transposed view (rows <-> columns)


---
## 2.5 Array methods

- A NumPy ndarray provides many built-in methods that operate on the array or return information about it. Most of these methods return a new array or a computed value derived from the data.

In [ ]:
# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape the array to 3 rows and 2 columns
reshaped = a.reshape(3, 2)
print("Reshaped array:\n", reshaped)

# Flatten the array to 1D
flattened = a.flatten()
print("\nFlattened array:", flattened)

In [ ]:
# --- Max and Min ---
print("Max element:", a.max())                  # ndarray.max()
print("Index of max (flattened):", a.argmax())  # ndarray.argmax()
print("Min element:", a.min())                  # ndarray.min()
print("Index of min (flattened):", a.argmin())  # ndarray.argmin()

In [ ]:
# --- Rounding ---
arr_float = np.array([[1.234, 2.567], [3.891, 4.456]])
rounded = arr_float.round(1)             # Round to 1 decimal
print("Rounded array:\n", rounded)

In [ ]:
# --- Trace ---
print("Trace (sum of diagonal):", a.trace())  # Sum along main diagonal

In [ ]:
# --- Sum, Cumsum, Mean ---
print("Sum of all elements:", a.sum())
print("Cumulative sum along rows:\n", a.cumsum(axis=1))
print("Mean along columns:", a.mean(axis=0))

In [ ]:
# --- Variance and Standard Deviation ---
print("Variance of all elements:", a.var())
print("Standard deviation:", a.std())

In [ ]:
# --- Logical checks ---
print("All elements > 0?", (a > 0).all())
print("Any element > 5?", (a > 5).any())

---
## 2.6 Arithmetic and linear algebra


In [ ]:
# Create example arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Array a:\n", a)
print("Array b:\n", b)


In [ ]:
# Addition (elementwise)
print("Addition (a + b):\n", a + b)

# Subtraction (elementwise)
print("Subtraction (a - b):\n", a - b)

# Multiplication (elementwise)
print("Elementwise multiplication (a * b):\n", a * b)

# Division (elementwise)
print("Elementwise division (a / b):\n", a / b)

# Exponentiation (elementwise)
print("Elementwise power (a ** 2):\n", a ** 2)

# Modulo (elementwise)
print("Elementwise modulo (b % a):\n", b % a)

In [ ]:
# Matrix multiplication
matmul = a @ b  # or np.matmul(a, b)
print("Matrix multiplication (a @ b):\n", matmul)

# Dot product
dot = np.dot(a[0], b[0])
print("Dot product (np.dot(a[0], b[0])):\n", dot)

# Transpose
print("Transpose of a (a.T):\n", a.T)

# Determinant
det = np.linalg.det(a)
print("Determinant of a:", det)

# Inverse
inv = np.linalg.inv(a)
print("Inverse of a:\n", inv)

# Eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(a)
print("Eigenvalues of a:", eigvals)
print("Eigenvectors of a:\n", eigvecs)

# Norms
norm_a0 = np.linalg.norm(a[0])
print("Frobenius norm of a[0]:", norm_a0)

---
## 2.7 Miscellaneous

**NumPy** provides optimized **mathematical functions** that work directly on entire arrays (`np.array` objects). These functions are implemented in **compiled C code**, which makes them **very fast**. They automatically apply the operation **elementwise** to all elements in the array — this is called **vectorization**.

In [ ]:
# These are elementwise functions that operate efficiently on ndarrays.

# Create an example array
a = np.array([0, np.pi/4, np.pi/2, np.pi])
print("Array a:\n", a)

# Elementwise trigonometric functions
print("sin(a):", np.sin(a))

In [ ]:
b = np.array([1, 2, 3, 4])
print("Array b:\n", b)

# Exponential
print("Exponential (e^b):", np.exp(b))

# Logarithms
print("Natural log (ln(b)):", np.log(b))
print("Log base 10:", np.log10(b))

# Power
print("b cubed:", np.power(b, 3))
c = np.array([1.234, 5.678, -9.1011])

# Round to nearest integer
print("Rounded:", np.round(c))

# Floor and ceiling
print("Floor:", np.floor(c))
print("Ceil:", np.ceil(c))

# Absolute values
print("Absolute values:", np.abs(c))
d = np.array([1, 2, 3, 4, 5])

# Sum/product
print("Sum:", np.sum(d))
print("Product:", np.prod(d))

---
## 2.8 Python lists vs NumPy arrays

Python lists are flexible but **slow and memory-inefficient** for numerical computations.
NumPy arrays (`ndarray`) store data in **contiguous memory** and support **vectorized operations**, making them much faster and smaller in memory footprint.

Let's compare both in terms of **execution speed** and **memory usage**.

In [ ]:
import time, sys

# Create a large list and a NumPy array
n = 1_000_000
py_list = list(range(n))
np_array = np.arange(n)

# Compare memory usage of both objects
list_mem = sys.getsizeof(py_list) + sum(sys.getsizeof(x) for x in py_list)
array_mem = np_array.nbytes
print(f"Python list memory: {list_mem / 1e6:.2f} MB")
print(f"NumPy array memory: {array_mem / 1e6:.2f} MB")
print(f"Memory ratio (list / array): {list_mem / array_mem:.1f}×")

# Compute 2x Python list
list_start = time.time()
list_result = [x * 2 for x in py_list]
list_end = time.time()
print(f"Python list time: {list_end - list_start:.5f} s")

# Compute 2x NumPy array
array_start = time.time()
array_result = np_array * 2
array_end = time.time()
print(f"NumPy array time: {array_end - array_start:.5f} s")
print(f"Execution speed ratio (list / array): {(list_end - list_start) / (array_end - array_start):.1f}×")

**Observation:**

- NumPy operations are much faster because they run in optimized C loops rather than Python loops.
- NumPy arrays use far less memory because all elements share the same data type and they are stored in an efficient way

➡️ This demonstrates the two biggest advantages of NumPy:
1. **Vectorization** (no explicit loops)
2. **Efficient memory representation**

---
## 2.9  🏠 Homework: NumPy Arrays in Data Science

### Task Overview
In this assignment, you will practice working with **NumPy arrays** and **mathematical functions** to perform a mini data analysis. You will simulate a small part of a **data preprocessing pipeline** — a common step in data science when dealing with multivariate datasets.

### Your Task

1. **Generate synthetic data:**
   - Create a NumPy array `data` of shape **(100, 10)** — representing 100 samples and 10 features.
   - The values should be drawn from a **normal distribution** with mean = 50 and standard deviation = 10 using
      `np.random.normal(loc=50, scale=10, size=(100, 10))`.
   - Print the shape, data type, and the **first 5 rows** of the array.

2. **Data cleaning:**
   - Replace all values **smaller than 20** or **larger than 80** with `np.nan` (treat them as outliers).
   - Print how many `np.nan` values are now in the array.

3. **Handle missing values:**
   - Compute the **mean of each column** ignoring missing values (`np.nanmean`).
   - Replace all `np.nan` values in each column with that column’s mean.

4. **Data transformation:**
   - **Standardize each column** so that it has mean 0 and standard deviation 1.
   - Create a new array where:
     - all positive standardized values are replaced with their **square roots**,
     - negative values remain unchanged.
   - For the first 5 rows, also compute the **exponential (`np.exp`)** of all standardized values and print the result.

5. **Array indexing and logical operations:**
   - Compute the **75th percentile** for each column.
   - Create a Boolean mask that marks all values above the 75th percentile.
   - Print how many such “high” values there are in total.
   - Replace all values **below the 25th percentile** (computed column-wise) with the 25th percentile value (a simple form of *winsorization*).

6. **Descriptive statistics:**
   - Compute and print for the final cleaned dataset:
     - column-wise **mean**, **median**, **variance**, and **standard deviation**,
     - the **overall mean** of the entire array,
     - and the **minimum and maximum** values per column.

### ✍️ Hints
- Use functions such as `np.mean`, `np.std`, `np.nanmean`, `np.isnan`, `np.where`, `np.percentile`, `np.sqrt`, and `np.exp`.
- Remember to specify the `axis` argument when computing column-wise statistics (`axis=0`).
- Use **vectorized operations** — avoid `for` loops.
- Include **comments or docstrings** to make your code clear and readable.


---
## Your solution:

In [16]:
#ukol cislo 1
#vytvoreni array
matice=np.random.normal(loc=50, scale=10, size=(100, 10))
#vypsani pozadavonych hodnot
print(matice.shape)
print(matice.dtype)
matice[:5]

(100, 10)
float64


array([[33.53933951, 50.36470071, 33.09988702, 30.3380762 , 39.16568098,
        46.32066953, 44.24472876, 58.72847464, 42.82992342, 61.78031194],
       [48.13346252, 31.71155048, 51.86809342, 62.36770953, 36.53994562,
        50.02388935, 49.3673453 , 51.2934968 , 44.23328566, 55.78860665],
       [50.12340304, 44.28758436, 62.45839794, 43.13964547, 56.43992847,
        59.68660504, 59.43261316, 55.39236756, 39.21328004, 42.56958223],
       [50.38144569, 44.59785554, 69.31153539, 50.80080581, 45.26966467,
        68.3664297 , 48.21924774, 54.99775111, 48.64324221, 41.14643855],
       [50.77257012, 49.58929355, 42.03783249, 63.79624606, 51.54378081,
        68.41421911, 54.18025872, 36.86689328, 34.29052206, 44.19094656]])

In [44]:
#ukol cislo 2
#vytvoreni kopie matice
matice2=matice.copy()
#nahrazeni pozadovanych hodnot
matice2[matice2<20]=np.nan
matice2[matice2>80]=np.nan
#pocet outliers
print(np.count_nonzero(np.isnan(matice2)))

1


In [50]:
#ukol cislo 3
#zjisteni prumeru sloupce
prumer_sloupcu=np.nanmean(matice2,axis=0)
#zjsiteni indexu, kde se nachazi nan values
index=np.where(np.isnan(matice2))
#nahrazeni nan values prumerem sloupce
matice2[index]=np.take(prumer_sloupcu,index[1])
matice2

array([[33.53933951, 50.36470071, 33.09988702, 30.3380762 , 39.16568098,
        46.32066953, 44.24472876, 58.72847464, 42.82992342, 61.78031194],
       [48.13346252, 31.71155048, 51.86809342, 62.36770953, 36.53994562,
        50.02388935, 49.3673453 , 51.2934968 , 44.23328566, 55.78860665],
       [50.12340304, 44.28758436, 62.45839794, 43.13964547, 56.43992847,
        59.68660504, 59.43261316, 55.39236756, 39.21328004, 42.56958223],
       [50.38144569, 44.59785554, 69.31153539, 50.80080581, 45.26966467,
        68.3664297 , 48.21924774, 54.99775111, 48.64324221, 41.14643855],
       [50.77257012, 49.58929355, 42.03783249, 63.79624606, 51.54378081,
        68.41421911, 54.18025872, 36.86689328, 34.29052206, 44.19094656],
       [39.07650114, 43.80536997, 54.36320467, 78.65057328, 58.90964088,
        43.79680595, 40.79370383, 56.41465616, 43.77997267, 52.91676226],
       [59.05230965, 47.47501055, 44.82784429, 38.88740036, 65.010216  ,
        49.20311153, 45.00765593, 24.65814725

In [65]:
#ukol cislo 4
#zjisteni hodnot mean a std
std=np.std(matice2,axis=0)
mean=np.mean(matice2,axis=0)
#upraveni na pozadovane hodnoty
matice2=(matice2-mean)/std
#vypsani vysledku
print(np.mean(matice2,axis=0))
print(np.std(matice2,axis=0))
#vytvoreni nove matice
matice3=matice2.copy()
#umocneni kaldnych hodnot
matice3[matice3>0]=np.sqrt(matice3[matice3>0])
#vytvoreni dalsi matice
matice4=matice3.copy()
#proved expontential
matice4[:5]=np.exp(matice4[:5])
matice4[:5]


[ 2.68882139e-18 -6.66133815e-18  1.36002321e-17  8.88178420e-18
 -5.55111512e-18  0.00000000e+00  5.55111512e-18 -2.22044605e-18
 -6.66133815e-18 -9.99200722e-18]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[-1.74163177 -0.09321994 -1.36448216 -1.76043499 -1.00447936 -0.30870567
  -0.57349097  0.93931961 -0.59679047  1.00513214]
 [-0.22784513 -1.82697706  0.42949771  1.189174   -1.28834288  0.25204856
  -0.05307971  0.41490648 -0.45997865  0.65128703]
 [-0.02143701 -0.65807058  1.02883039 -0.49162636  0.92898245  1.01724599
   0.9846116   0.75077505 -0.94937199 -0.86892607]
 [ 0.07299766 -0.62923176  1.27439601  0.51739562 -0.34458869  1.38103357
  -0.16971598  0.72523804 -0.03005814 -1.0081397 ]
 [ 0.21423898 -0.16529183 -0.62682858  1.24728589  0.57766314  1.38277161
   0.66020341 -1.20585241 -1.42928479 -0.71032226]]


array([[0.17523423, 0.91099311, 0.25551296, 0.17197004, 0.36623526,
        0.7343969 , 0.56355465, 2.55824022, 0.55057589, 2.73226828],
       [0.79624757, 0.16089922, 1.53648557, 3.28436721, 0.27572732,
        1.28665852, 0.94830442, 1.51422912, 0.63129713, 1.91800777],
       [0.97879113, 0.51784952, 2.79779159, 0.61163085, 2.53193151,
        2.76556787, 2.67677201, 2.11864143, 0.38698398, 0.41940172],
       [1.07572802, 0.53300112, 3.57654055, 1.67765272, 0.70851171,
        3.97901208, 0.84390447, 2.06522265, 0.97038912, 0.36489717],
       [1.2389187 , 0.8476463 , 0.53428355, 3.48088264, 1.78186958,
        3.9859338 , 1.93518592, 0.29943665, 0.23948014, 0.49148579]])

In [80]:
#ukol cislo 5
#zjisteni percentilu 75
percentile=np.percentile(matice3,75,axis=0)
#vytvoreni mask s boolean hodnotami
mask=matice3<percentile
#zjisteni hodnot vetsich nez 75 percentil
pocet=(np.count_nonzero(mask==False))
#zjisteni hodnoty pro percenitl 25
percentile25=np.percentile(matice3,25,axis=0)
#nahrazeni hodnot
matice3 = np.where(matice3 < percentile25, percentile25, matice3)
matice3


250


array([[-6.35824577e-01, -9.32199441e-02, -6.89786234e-01,
        -6.40415364e-01, -5.63730450e-01, -3.08705667e-01,
        -5.73490972e-01,  9.39319609e-01, -5.93340419e-01,
         1.00513214e+00],
       [-2.27845126e-01, -6.31034182e-01,  4.29497708e-01,
         1.18917400e+00, -5.63730450e-01,  2.52048565e-01,
        -5.30797069e-02,  4.14906477e-01, -4.59978646e-01,
         6.51287029e-01],
       [-2.14370140e-02, -6.31034182e-01,  1.02883039e+00,
        -4.91626361e-01,  9.28982453e-01,  1.01724599e+00,
         9.84611595e-01,  7.50775048e-01, -5.93340419e-01,
        -7.35234501e-01],
       [ 7.29976588e-02, -6.29231756e-01,  1.27439601e+00,
         5.17395624e-01, -3.44588688e-01,  1.38103357e+00,
        -1.69715980e-01,  7.25238040e-01, -3.00581359e-02,
        -7.35234501e-01],
       [ 2.14238980e-01, -1.65291828e-01, -6.26828585e-01,
         1.24728589e+00,  5.77663137e-01,  1.38277161e+00,
         6.60203406e-01, -5.76978876e-01, -5.93340419e-01,
        -7.

In [83]:
#ukol cisl 6
#mean pro kazdy sloupec
print(np.mean(matice3,axis=0))
#median pro kazdy sloupec
print(np.median(matice3,axis=0))
#std pro kazdy sloupec
print(np.std(matice3,axis=0))
#var pro kazdy sloupec
print(np.var(matice3,axis=0))
#mean pro celoy array
print(np.mean(matice3))
#min pro kazdy sloupec
print(np.min(matice3,axis=0))
#max pro kazdy sloupec
print(np.max(matice3,axis=0))


[0.14372605 0.17420746 0.15136933 0.15906366 0.20219444 0.18238169
 0.10175213 0.16233552 0.19338701 0.14959364]
[-0.07657132  0.21325746 -0.02549225 -0.0249791   0.07699363  0.10205003
 -0.12956834 -0.0656981   0.11295022  0.08398329]
[0.7153989  0.71396094 0.73736825 0.71043506 0.67641901 0.68419339
 0.75131666 0.68711243 0.68264607 0.75792424]
[0.51179559 0.50974023 0.54371193 0.50471797 0.45754268 0.4681206
 0.56447672 0.47212349 0.46600566 0.57444915]
0.1620010949590123
[-0.63582458 -0.63103418 -0.68978623 -0.64041536 -0.56373045 -0.56520749
 -0.7251092  -0.57697888 -0.59334042 -0.7352345 ]
[1.66660672 1.56892026 1.51626225 1.74011115 1.56734511 1.46884764
 1.735796   1.65853481 1.66608599 1.50146625]
